Repository AY2425S2-CS2113-T11b-1/tp, pull requests merged in 2025-03, with the labels that each got.

#22 Resolved issue where dish names are added with dish flag
  data/cookingaids.json
  src/main/java/seedu/cookingaids/Commands/DeleteCommand.java
  src/main/java/seedu/cookingaids/Parser/Parser.java
  src/test/java/seedu/cookingaids/CookingAidsTest.java
  src/test/java/seedu/cookingaids/StorageTest.java
Labels: type.Bug, severity.Low

#27 Revert code deletions in #21
  src/main/java/seedu/cookingaids/Commands/DisplayCommand.java
  src/main/java/seedu/cookingaids/CookingAids.java
  src/main/java/seedu/cookingaids/Items/ExpiryDate.java
  src/main/java/seedu/cookingaids/collections/DishCalendar.java
  src/main/java/seedu/cookingaids/collections/IngredientStorage.java
  src/main/java/seedu/cookingaids/collections/RecipeBank.java
  src/main/java/seedu/cookingaids/commands/AddCommand.java
  src/main/java/seedu/cookingaids/commands/DeleteCommand.java
  src/main/java/seedu/cookingaids/commands/DisplayCommand.java
  src/main/java/seedu/cookingaids/commands/HelpCommand.java
  src/main/java/seedu/cookingaids/items/Dish.java
  src/main/java/seedu/cookingaids/items/DishDate.java
  src/main/java/seedu/cookingaids/items/ExpiryDate.java
  src/main/java/seedu/cookingaids/items/Food.java
  src/main/java/seedu/cookingaids/items/Ingredient.java
  src/main/java/seedu/cookingaids/items/Recipe.java
  src/main/java/seedu/cookingaids/parser/Parser.java
  src/main/java/seedu/cookingaids/storage/Storage.java
  src/main/java/seedu/cookingaids/ui/Ui.java
  src/test/java/seedu/cookingaids/CookingAidsTest.java
  src/test/java/seedu/cookingaids/StorageTest.java
  src/test/java/seedu/cookingaids/commands/AddCommandTest.java
  src/test/java/seedu/cookingaids/commands/DeleteCommandTest.java
  src/test/java/seedu/cookingaids/commands/DisplayCommandTest.java
  src/test/java/seedu/cookingaids/commands/HelpCommandTest.java
Labels: type.Bug

#30 Resolved #25
  src/main/java/seedu/cookingaids/collections/DishCalendar.java
  src/main/java/seedu/cookingaids/collections/IngredientStorage.java
  src/main/java/seedu/cookingaids/collections/RecipeBank.java
  src/main/java/seedu/cookingaids/items/Recipe.java
  src/test/java/seedu/cookingaids/commands/DeleteCommandTest.java
Labels: type.Task, priority.High

#41 Resolved #40
  src/main/java/seedu/cookingaids/commands/HelpCommand.java
  src/main/java/seedu/cookingaids/commands/ListCommand.java
  src/main/java/seedu/cookingaids/parser/Parser.java
Labels: type.Enhancement

#43 Resolved #42
  META-INF/MANIFEST.MF
  src/main/java/seedu/cookingaids/collections/DishCalendar.java
  src/main/java/seedu/cookingaids/collections/IngredientStorage.java
  src/main/java/seedu/cookingaids/collections/RecipeBank.java
  src/main/java/seedu/cookingaids/commands/AddCommand.java
  src/main/java/seedu/cookingaids/commands/HelpCommand.java
  src/main/java/seedu/cookingaids/items/Dish.java
  src/main/java/seedu/cookingaids/parser/Parser.java
  src/out/artifacts/tp_jar/tp.jar
  src/out/artifacts/tp_main_jar/tp.main.jar
  src/test/java/seedu/cookingaids/collections/IngredientStorageTest.java
  src/test/java/seedu/cookingaids/commands/DeleteCommandTest.java
  src/test/java/seedu/cookingaids/items/IngredientTest.java
Labels: severity.High

#47 PR
  build.gradle
  src/main/java/seedu/cookingaids/collections/IngredientStorage.java
  src/main/java/seedu/cookingaids/items/Ingredient.java
  src/main/java/seedu/cookingaids/parser/Parser.java
  src/main/java/seedu/cookingaids/storage/Storage.java
  src/main/java/seedu/cookingaids/ui/Ui.java
  src/test/java/seedu/cookingaids/StorageTest.java
  src/test/java/seedu/cookingaids/collections/IngredientStorageTest.java
  src/test/java/seedu/cookingaids/items/IngredientTest.java
Labels: priority.High

#48 Fixed Ingredients class to include Json properties
  src/main/java/seedu/cookingaids/items/Ingredient.java
Labels: type.Bug

#45 Resolved #42
  data/cookingaids.json
  src/test/java/seedu/cookingaids/commands/AddCommandTest.java
Labels: type.Task

#66 Added expired flag for ingredients, more functions for ingredient sto…
  src/main/java/seedu/cookingaids/collections/IngredientStorage.java
  src/main/java/seedu/cookingaids/commands/AddCommand.java
  src/main/java/seedu/cookingaids/items/Ingredient.java
  src/main/java/seedu/cookingaids/parser/Parser.java
  src/test/java/seedu/cookingaids/items/IngredientTest.java
Labels: priority.Medium

#73 Started on developer guide
  docs/DeveloperGuide.md
  docs/img.png
  src/main/java/seedu/cookingaids/commands/AddCommand.java
  src/main/java/seedu/cookingaids/diagrams/bigPicture.puml
Labels: priority.High

#77 Edited DG
  docs/DeveloperGuide.md
  docs/img_1.png
  docs/img_2.png
  src/main/java/seedu/cookingaids/diagrams/Collection.puml
Labels: priority.High

#78 Updated UG, added an assert
  data/cookingaids.json
  docs/UserGuide.md
  src/main/java/seedu/cookingaids/items/Ingredient.java
Labels: priority.High
